name: default
channels:
- conda-forge
- nodefaults
dependencies:
- matplotlib *
- numba <0.66
- numpy <2.5
- pandas *
- scipy *
- scikit-sparse *
- ipyparallel *
- ipykernel *
- pytables *
- tqdm *
- meshio *
- python >=3.11,<=3.14
- pip
- dill
- pip:
  - datoviz

