Particles count: 2080
Packing size: 64.90666419935816 64.90666419935816 64.90666419935816
Generation start: 0
Seed: 1354431465
Steps to write: 100
Boundaries mode: 1
Contraction rate: 0.1
1. boundaries mode: 1 - bulk; 2 - ellipse (inscribed in XYZ box, Z is length of an ellipse); 3 - rectangle
2. generationMode = 1 (Poisson, R) or 2 (Poisson in cells, S)