schema_version: 1

context:
  version: "1.0"

package:
  name: treillis
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/treillis/treillis-${{ version }}.tar.gz
  sha256: 70f8bac859c2c571cafef0c02425cb8ab55a9716f816713d8d96479b296ee5b2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.11,<=3.14
    - pip
  run:
    - python >=3.11,<=3.14

tests:
  - python:
      imports:
        - treillis
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A comprehensive library to generate and simulate 2D/3D microlattices.
  license: LGPL-3.0-only
  license_file: LICENSE
  homepage: https://pypi.org/project/treillis/

extra:
  recipe-maintainers:
    - 4nile
